# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{time_zone_detection}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Pavlo Lysov, Boris Babusenko"]
  s.date = %q{2010-12-10}
  s.description = %q{See README}
  s.email = %q{boris@cleverua.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "js_files/jquery.cookie.js",
    "js_files/time_zone_detection.js",
    "lib/client_timezone_detection.rb",
    "lib/client_timezone_detection/client_timezone_railtie.rb",
    "lib/client_timezone_detection/controller_helpers.rb",
    "lib/client_timezone_detection/view_helpers.rb",
    "lib/client_timezone_detection_install.rb",
    "test/helper.rb",
    "test/test_time_zone_detection.rb"
  ]
  s.homepage = %q{http://github.com/cleverua/time_zone_detection}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Gem for detection client time zone}
  s.test_files = [
    "test/helper.rb",
    "test/test_time_zone_detection.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.1"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
  end
end

